### ISSUE TITLE
[SubTask]docsCreation : 2. 開立工作票

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/KnowledgeManagement#67]
- [x] 開票的方法步驟
- [x] 票的定義、內容
- [x] 畫面範例
- [x] 將[討論](https://github.com/CAFECA-IO/KnowledgeManagement/issues/67#issuecomment-1880354753)內容補齊進文章
- [x] 統一所有專案的狀態設定 [Link](https://github.com/CAFECA-IO/KnowledgeManagement/issues/67#issuecomment-1880430343) 
- [x] [github-project-automation](https://github.com/apps/github-project-automation) Setting [Link](https://github.com/CAFECA-IO/KnowledgeManagement/issues/67#issuecomment-1880434807)

**Comment by godmmt** [comment]
# 開立工作票

## 開立工作票步驟

1. 於 GitHub 新增 issue
2. 新增標題、敘述
3. 選擇指定對象 Assignee，通常為自己
4. 選擇標籤 Labels：
- 首先，在 **1** 至 **8** 等純數字的紅色標籤之中選擇一個，此為我們預計這張工作票會完成的時數，1表示為1小時，以此類推。
- 接著選擇這張工作票的種類，假設此張工作票會產出文件就選擇documentation、會產出程式就選擇 enhancement。
5. 選擇專案 Projects，並且指定狀態。
初始狀態應為 `To Do`，視情況選擇適當的狀態，假設我們是建立當天要執行的工作票，即可直接選擇 `Daily Paln`。
6. 此張工作票如果有產生 Branch 或 Pull Request，就在 Development 綁定該分支和PR。

**Comment by godmmt** [comment]
took 2.5 hours

done.

**Comment by godmmt** [comment]
took 1 hour

Total time: 3.5 hours

done.

**Comment by godmmt** [comment]
針對 [CAFACA](https://github.com/orgs/CAFECA-IO/projects/5) & [BAIFA](https://github.com/orgs/CAFECA-IO/projects/11) & [ASICEX](https://github.com/orgs/CAFECA-IO/projects/17) 這三個專案，修改專案狀態選項的顏色，以及部分狀態新增註解。

![截圖 2024-01-05 上午10 53 34](https://github.com/CAFECA-IO/KnowledgeManagement/assets/105651918/3fb5e960-87df-4ab4-93a3-673bb5ce6edc)

**Comment by godmmt** [comment]
# 討論

- 欲變更項目：新增專案狀態欄位 Close date
- 需求目標：讓 PM 計算單子可以更有效率
- 解決方式：所有成員 Close issue 後在狀態欄位(Close date)點選“今日”日期。
- demo：
  ![截圖 2024-01-08 上午11 54 55](https://github.com/CAFECA-IO/KnowledgeManagement/assets/105651918/97ed945f-9c4f-472f-b46f-3a52a950e3f2)
- 預計結果：在專案的 dashboard 可依據時間篩選，讓 PM 可以更有效率的記錄前一週的單號。

**Comment by godmmt** [comment]
# 統一以下專案的狀態設定：

- [ ] [ASICEX](https://github.com/orgs/CAFECA-IO/projects/17)
- [ ] [BAIFA](https://github.com/orgs/CAFECA-IO/projects/11)
- [ ] [CAFECA](https://github.com/orgs/CAFECA-IO/projects/5)
- [ ] [TideBit](https://github.com/orgs/CAFECA-IO/projects/2)

**Comment by godmmt** [comment]
# [github-project-automation](https://github.com/apps/github-project-automation) Setting:


- [ ] [ASICEX](https://github.com/orgs/CAFECA-IO/projects/17)
- [ ] [BAIFA](https://github.com/orgs/CAFECA-IO/projects/11)
- [ ] [CAFECA](https://github.com/orgs/CAFECA-IO/projects/5)
- [ ] [TideBit](https://github.com/orgs/CAFECA-IO/projects/2)
